### PR TITLE
Organize imports lexicographically

### PR DESCRIPTION
**Pull request by shamsimam**

### CODE REVIEW

**Comment by shamsimam** [comment]
Here is the code I used to get the ordering:
```
(defn parse-file
  [file-path]
  (try
    (-> file-path
        io/file
        slurp
        tr/read-string)
    (catch Exception e
      (println "ERROR:" (.getMessage e)))))

(defn sort-items
  "TODO"
  [imports]
  (sort (fn [a b] (compare (str a) (str b))) imports))

(defn organize-requires-and-imports
  "TODO"
  [parsed-ns]
  (letfn [(process-entries [entry operation]
            (-> entry
                rest
                sort-items
                (conj operation)))]
    (map (fn [entry]
           (if (and (seq? entry) (= "require" (-> entry first name)))
             (process-entries entry :require)
             (if (and (seq? entry) (= "import" (-> entry first name)))
               (process-entries entry :import)
               (if (and (seq? entry) (= "use" (-> entry first name)))
                 (process-entries entry :use)
                 entry))))
         parsed-ns)))

(defn process-file
  "TODO"
  [filepath]
  (let [current-ns (-> filepath
                       parse-file)
        sorted-ns (-> current-ns
                      organize-requires-and-imports
                      doall)]
    {:current-ns current-ns
     :sorted-ns sorted-ns}))

(test/deftest test-sorting
  (let [root-directory <FILL-YOUR-SOURCE-DIRECTORY>
        source-files (->> root-directory
                          io/file
                          file-seq
                          (filter #(not (.isDirectory ^File %))))]
    (doseq [source-file source-files]
      (println "Processing" (.getName source-file))
      (let [{:keys [current-ns sorted-ns]} (process-file source-file)]
        (when-not (= current-ns sorted-ns)
          (clojure.pprint/pprint sorted-ns))))))
```

**Comment by dposada** [comment]
Looks good to me. @wyegelwel ?

**Comment by shamsimam** [comment]
Rebased to handle conflicts.

**Comment by shamsimam** [comment]
Bump

**Pull request merged**
