### PR TITLE
Cleanup comments and add a standalone mesos example

### PR DESCRIPTION
**Pull request by tnn1t1s**
I tried to standardize on a comment format 
     - comment starts above relevant line
     - no more than 80 chars on line
     - two semicolons at start, and one to follow.

### CODE REVIEW

**Comment by leifwalsh** [comment]
This is a bit of a weird style for lisp, where did you see it? 




Emac a is quite helpful with a style like this, obviously: http://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html




-- 
Cheers,
Leif

**Comment by leifwalsh** [comment]
Emacs. Come on, ios. 



-- 
Cheers,
Leif

**Comment by dgrnbrg** [comment]
The clojure style is 2 semicolons if the comment is on its own line, one
comment if it's sharing a line with code, and 3 semicolons if it's
toplevel. We use that everywhere; I think it's an emacs thing.

**Comment by leifwalsh** [comment]
@dgrnbrg see the link I pasted



-- 
Cheers,
Leif

**Pull request closed without merging**
