### PR TITLE
Adds version number to /debug and framework name

### PR DESCRIPTION
**Pull request by dposada**

### CODE REVIEW

**Comment by dposada** [comment]
Not sure if there's a specific reason. I followed the pattern that was in place. Why don't you like them as variables?

**Comment by shamsimam** [comment]
I prefer running a function to query for the values rather than eagerly computing them.

**Comment by dposada** [comment]
If we put them in a function, then each time someones hits `/debug`, it will look up the resource. We could make them be `delay`s, but that seems like overkill. Thoughts?

**Comment by shamsimam** [comment]
`delay` is not a bad trade-off, middle ground :)

**Pull request merged**
