### PR TITLE
fixes the partial call to render-jobs-for-response from destroy-jobs-handler

### PR DESCRIPTION
**Pull request by shamsimam**

### CODE REVIEW

**Comment by pschorf** [comment]
Can you add an integration test for this?

**Comment by shamsimam** [comment]
@pschorf okay

**Comment by shamsimam** [comment]
Turns out `handle-ok` is unused in our deletes. I strengthened the assertions on the unit tests. We already have integration tests for delete.

**Comment by pschorf** [comment]
Yeah I was honestly surprised the tests were passing as it was. Thanks for cleaning up the dead code.

**Pull request merged**
