### PR TITLE
Issue #369 - rename fid to framework-id

### PR DESCRIPTION
**Pull request by shamsimam**

### CODE REVIEW

**Comment by shamsimam** [comment]
Passing build: https://travis-ci.org/twosigma/Cook/builds/241048544

**Comment by dposada** [comment]
Any chance we can wait to merge this until after PR #367 is merged?

**Comment by shamsimam** [comment]
@dposada sgtm

**Comment by shamsimam** [comment]
Rebased, this branch is ready for another round of review :)

Passing build: https://travis-ci.org/twosigma/Cook/builds/246056374

**Comment by shamsimam** [comment]
Can we get the ball rolling to get this merged?

**Comment by dposada** [comment]
@shamsimam yes, let me get PR #367 ready for another pass

**Comment by shamsimam** [comment]
Rebased, ready to merge. Passing build: https://travis-ci.org/twosigma/Cook/builds/248640939

**Pull request merged**
