### PR TITLE
Removes TS-specific info

### PR DESCRIPTION
**Pull request by dposada**

### CODE REVIEW

**Comment by wyegelwel** [comment]
@dposada can you rebase?

**Comment by dposada** [comment]
Yes will do

**Comment by dposada** [comment]
Rebased

**Comment by wyegelwel** [comment]
LGTM. Thanks for doing some spring cleaning =)

Will merge later today if it someone else doesn't have time to look.

**Comment by dposada** [comment]
@wyegelwel Can we merge this?

**Pull request merged**
