### PR TITLE
Update the version strings in the sub-projects

### PR DESCRIPTION
**Pull request by shamsimam**

### CODE REVIEW

**Comment by sradack** [comment]
Are we going to do this for every release?

**Comment by shamsimam** [comment]
@sradack that is the intent. Henceforth, we can do this when we prepare the changelog.

**Comment by pschorf** [comment]
I just opened a PR for 1.3.3, I can just do this in that PR

**Comment by shamsimam** [comment]
@pschorf  +1

**Comment by shamsimam** [comment]
You will need to update the versions to 1.3.4* in the files after the 1.3.3 release

**Pull request closed without merging**
