### PR TITLE
Fixes support for host placement + straggler handling in Java client

### PR DESCRIPTION
**Pull request by dposada**

### CODE REVIEW

**Comment by wyegelwel** [comment]
This code all looks good, thought there are a lot of changes. What was the specific thing that needed to be fixed?

**Comment by dposada** [comment]
Without these changes, attempting to submit a job group with an `attribute-equals` host placement or a `quantile-deviation` straggler handling through the job client doesn't work because it's sending underscores in the JSON posted to the API instead of dashes. I fixed that and also added some assertions to the test that was attempting to submit these.

**Comment by wyegelwel** [comment]
Ok, makes sense, though I was under the impression that the api would accept either underscore or dash. Glad to know the answer.

**Comment by dposada** [comment]
@wyegelwel I believe the API will accept either underscore or dash for keys, but not (necessarily) for values

**Pull request merged**
