### PR TITLE
Cook Executor: adds support for task environment in cook executor

### PR DESCRIPTION
**Pull request by shamsimam**
This PR gets us closer to the Mesos command executor algorithm of [setting up the environment](https://github.com/apache/mesos/blob/master/src/launcher/executor.cpp#L573):
```
    // Determine the environment for the command to be launched.
    // The priority of the environment should be:
    //  1) User specified environment in CommandInfo.
    //  2) Environment returned by isolators (`taskEnvironment`).
    //  3) Environment passed from agent (`os::environment`).
```

### CODE REVIEW

**Comment by dposada** [comment]
Is not having this causing issues?

**Comment by shamsimam** [comment]
It is not currently as all three environments are configured to be the same from the scheduler.

**Comment by dposada** [comment]
So do we need this?

**Comment by shamsimam** [comment]
From a correctness perspective - Yes. Since we want to get closer to the Mesos command executor.

Also, this allows the scheduler to be smarter with how it propagates the environments in the task description.

**Comment by dposada** [comment]
Is there any practical effect to the end-user? I looked at the code and it makes sense, I'm just trying to figure out what real effects this has

**Comment by shamsimam** [comment]
There is no effect on the end-user. This change will allow the scheduler to be smarter about what environment it sends to the agent, executor and task.

**Comment by dposada** [comment]
Got it. I would vote to put the corresponding Cook Scheduler changes in this PR as well, along with an integration test that shows the behavior change

**Comment by shamsimam** [comment]
I added some log statements to print the executor process environment, environment received in the register call, and environment received in the launch task call. All three appear to be built from the same environment in the scheduler. As such this PR is unneeded and any restrictions we want to place on the environment should be built in the scheduler.

Environment of executor process (common entries listed first):
```
'COOK_JOB_UUID': '3e7ce072-911e-431b-9be4-b7d6913b3074',
'EXECUTOR_DEFAULT_PROGRESS_OUTPUT_NAME': 'stdout',
'EXECUTOR_LOG_LEVEL': 'INFO',
'EXECUTOR_MAX_MESSAGE_LENGTH': '512',
'PROGRESS_REGEX_STRING': 'progress:\\s+([0-9]*\\.?[0-9]+)($|\\s+.*)',
'PROGRESS_SAMPLE_INTERVAL_MS': '300000',
'SOURCE-CMD': 'COMMAND-ENV',
'_': '/Users/shamsimam/projects/github-projects/twosigma-cook/executor/dist/cook-executor-local/cook-executor-local',
'LIBPROCESS_IP': '127.0.0.3',
'LIBPROCESS_PORT': '0',
'MESOS_AGENT_ENDPOINT': '127.0.0.3:5051',
'MESOS_CHECKPOINT': '1',
'MESOS_DIRECTORY': '/Users/shamsimam/Desktop/temp/mesos/agent-3/slaves/e798332a-25d0-4f5d-93bf-98f6c7193204-S0/frameworks/cook-framework-1514309922/executors/546e3cde-a5bd-432b-8aa9-3c7cd21ad737/runs/ddc636d2-b30f-4cbe-91b4-f7199fc662c6',
'MESOS_EXECUTOR_ID': '546e3cde-a5bd-432b-8aa9-3c7cd21ad737',
'MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD': '5secs',
'MESOS_FRAMEWORK_ID': 'cook-framework-1514309922',
'MESOS_HTTP_COMMAND_EXECUTOR': '0',
'MESOS_NATIVE_JAVA_LIBRARY': '/usr/local/Cellar/mesos/1.3.0/lib/libmesos-1.3.0.dylib',
'MESOS_NATIVE_LIBRARY': '/usr/local/Cellar/mesos/1.3.0/lib/libmesos-1.3.0.dylib',
'MESOS_RECOVERY_TIMEOUT': '15mins',
'MESOS_SANDBOX': '/Users/shamsimam/Desktop/temp/mesos/agent-3/slaves/e798332a-25d0-4f5d-93bf-98f6c7193204-S0/frameworks/cook-framework-1514309922/executors/546e3cde-a5bd-432b-8aa9-3c7cd21ad737/runs/ddc636d2-b30f-4cbe-91b4-f7199fc662c6',
'MESOS_SLAVE_ID': 'e798332a-25d0-4f5d-93bf-98f6c7193204-S0',
'MESOS_SLAVE_PID': 'slave(1)@127.0.0.3:5051',
'MESOS_SUBSCRIPTION_BACKOFF_MAX': '2secs'
'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
'PWD': '/Users/shamsimam/Desktop/temp/mesos/agent-3/slaves/e798332a-25d0-4f5d-93bf-98f6c7193204-S0/frameworks/cook-framework-1514309922/executors/546e3cde-a5bd-432b-8aa9-3c7cd21ad737/runs/ddc636d2-b30f-4cbe-91b4-f7199fc662c6',
'SHLVL': '1',
```

Environment received in `register` call:
```
'COOK_JOB_UUID': '3e7ce072-911e-431b-9be4-b7d6913b3074',
'EXECUTOR_DEFAULT_PROGRESS_OUTPUT_NAME': 'stdout',
'EXECUTOR_LOG_LEVEL': 'INFO',
'EXECUTOR_MAX_MESSAGE_LENGTH': '512',
'PROGRESS_REGEX_STRING': 'progress:\\s+([0-9]*\\.?[0-9]+)($|\\s+.*)'
'PROGRESS_SAMPLE_INTERVAL_MS': '300000',
'SOURCE-CMD': 'COMMAND-ENV',
```

Environment received in `launchTask` call:
```
'COOK_JOB_UUID': '3e7ce072-911e-431b-9be4-b7d6913b3074',
'EXECUTOR_DEFAULT_PROGRESS_OUTPUT_NAME': 'stdout',
'EXECUTOR_LOG_LEVEL': 'INFO',
'EXECUTOR_MAX_MESSAGE_LENGTH': '512',
'PROGRESS_REGEX_STRING': 'progress:\\s+([0-9]*\\.?[0-9]+)($|\\s+.*)'
'PROGRESS_SAMPLE_INTERVAL_MS': '300000',
'SOURCE-CMD': 'COMMAND-ENV',
```

**Comment by dposada** [comment]
Why did we close this?

**Pull request closed without merging**
