### PR TITLE
Analysis code for simulator traces

### PR DESCRIPTION
**Pull request by wyegelwel**

### CODE REVIEW

**Comment by wyegelwel** [comment]
Can we get this merged?

**Comment by wyegelwel** [comment]
@pschorf any feedback on this?

**Comment by DaoWen** [comment]
@wyegelwel - Do you still want to get this merged? I'd be happy to do the review to get this out of our PR backlog. If not, lets close it.

**Comment by wyegelwel** [comment]
If you don't mind doing the review I'd appreciate it

**Pull request merged**
