### PR TITLE
WIP: Convert files from Markdown to Asciidoc format

### PR DESCRIPTION
**Pull request by shamsimam**

### CODE REVIEW

**Comment by sradack** [comment]
Why are we converting to AsciiDoc?

**Comment by shamsimam** [comment]
@sradack We ( @DaoWen , @dposada and I) were talking about it for consistency of using one style for all documentation. I ended up doing it while waiting on the integration tests.

**Comment by shamsimam** [comment]
Notes: @wyegelwel mentioned offline that he prefers converting everything to Markdown format. @dposada also appears to favor that direction.

**Comment by dposada** [comment]
Can we delete the branch?

**Pull request closed without merging**
