### PR TITLE
Adding support for docker force pull image

### PR DESCRIPTION
**Pull request by m4ce**
This pull request adds support for force-image-pull option the the job's docker configuration.

### CODE REVIEW

**Comment by wyegelwel** [comment]
Hey Matteo, thanks for the PR! I'm excited to add this feature to Cook!

What steps did you take to test this?

**Comment by m4ce** [comment]
Hi @wyegelwel,

for the testing, it's a bit manual as you need to have the image:tag already pulled on the destination system and then have a newer version of the same image:tag available in the registry. I was testing with a private registry and custom docker images.

In the job's definition, I then used:

```
 "container": {"type": "DOCKER", "docker": {"image": "mycustomimage:latest", "network": "HOST", "force-pull-image": true}}
```

**Comment by wyegelwel** [comment]
Matteo, this looks good to me. With the most recent commit were you able to confirm that you are pulling the latest image? If you don't use force-pull does it use what is currently there?

**Comment by m4ce** [comment]
Hi @wyegelwel,

is it does, we have been using it for a few days now and it works fine.

Thanks,
Matteo

**Comment by wyegelwel** [comment]
Glad to hear it is working well! Thanks again for the pr.

**Pull request merged**
