### PR TITLE
Refactor http async pool client

### PR DESCRIPTION
**Pull request by jhn**

### CODE REVIEW

**Comment by dgrnbrg** [comment]
We should include @leifwalsh, who's doing other work on this code :)

**Comment by leifwalsh** [comment]
This is fine, this won't conflict on anything I'm doing



-- 
Cheers,
Leif

**Comment by dgrnbrg** [comment]
@jhn Can you please push these changes again to trigger a new build to confirm they pass the tests?

**Comment by leifwalsh** [comment]
@dgrnbrg whoops, didn't see you there.  These changes are innocuous enough they shouldn't affect the build.  Thanks, @jhn!

**Comment by jhn** [comment]
:thumbsup:

**Pull request merged**
